# SSH Key Pair for EC2 Instances
# In summary, ssh.tf automatically generates a secure SSH key pair, registers the public key with AWS in both your primary and secondary regions, and saves the private
# key securely on your local machine, ready for you to use for SSH access.

# Generate a new private key
resource "tls_private_key" "vpc_peering_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

# Create a key pair in the primary region
resource "aws_key_pair" "primary_key_pair" {
  provider   = aws.primary
  key_name   = "vpc-peering-key-${var.primary_region}"
  public_key = tls_private_key.vpc_peering_key.public_key_openssh
}

# Create a key pair in the secondary region
resource "aws_key_pair" "secondary_key_pair" {
  provider   = aws.secondary
  key_name   = "vpc-peering-key-${var.secondary_region}"
  public_key = tls_private_key.vpc_peering_key.public_key_openssh
}

# Save the private key to a local file
resource "local_file" "vpc_peering_private_key" {
  content         = tls_private_key.vpc_peering_key.private_key_pem
  filename        = "vpc-peering-key.pem"
  file_permission = "0400"
}

#1. `tls_private_key "vpc_peering_key"`:
#       * Purpose: This resource from the terraform-provider-tls generates a new RSA private key locally. This is the core of your SSH key pair.
#       * algorithm = "RSA": Specifies that the key should be an RSA key.
#       * rsa_bits = 2048: Sets the strength of the RSA key to 2048 bits.
#
#   2. `aws_key_pair "primary_key_pair"` and `aws_key_pair "secondary_key_pair"`:
#       * Purpose: These resources take the public key generated by tls_private_key and register it with AWS in the specified regions. This allows you to associate the#
#         key with EC2 instances.
# #      * provider = aws.primary (or aws.secondary): Indicates which AWS region (as defined by your provider configurations) this key pair should be created in.
#       * key_name = "vpc-peering-key-${var.primary_region}" (or secondary_region): Defines the name under which the key pair will appear in the AWS EC2 console for that
#         region. It includes the region name to make it unique and identifiable.
#       * public_key = tls_private_key.vpc_peering_key.public_key_openssh: This is the crucial part. It references the public key portion of the key pair generated by the#
#         tls_private_key resource, formatted for OpenSSH, and uploads it to AWS.#
#   3. `local_file "vpc_peering_private_key"`:#
#       * Purpose: This resource writes the private key portion of the generated key pair to a file on your local machine. This is the file you'll use to authenticate
#         when SSHing into your EC2 instances.
#       * content = tls_private_key.vpc_peering_key.private_key_pem: Takes the private key generated by the tls_private_key resource (in PEM format) and uses it as the
#         content for the local file.
# #      * filename = "vpc-peering-key.pem": Specifies the name of the file that will be created in your current working directory.
#       * file_permission = "0400": This is very important for security. It sets the file permissions to 0400, meaning only the owner (you) can read the file, and no one
#         can write to or execute it. This is the standard secure permission for SSH private keys.#